# Generated by Django 4.0.6 on 2022-08-25 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_address_municipality_ibge_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='account_id',
            new_name='account',
        ),
    ]
