# Generated by Django 4.0.6 on 2022-11-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='types',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='britday',
            field=models.DateField(blank=True),
        ),
    ]
