# Generated by Django 4.0.6 on 2022-08-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_request_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
