# Generated by Django 4.0.6 on 2022-08-31 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_delete_ticket'),
        ('account', '0003_rename_account_id_address_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='account/covers/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='Requisition',
        ),
    ]
