# Generated by Django 4.0.6 on 2022-11-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_address_types_alter_customer_britday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='britday',
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=15),
        ),
    ]
