# Generated by Django 4.0.6 on 2022-11-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customer_britday_alter_customer_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='britday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
