# Generated by Django 4.0.6 on 2022-08-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_ticket_options_and_more'),
        ('account', '0004_alter_request_is_paid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Requisition',
        ),
        migrations.AlterModelOptions(
            name='requisition',
            options={'verbose_name': 'requisition', 'verbose_name_plural': 'requisitions'},
        ),
    ]
