# Generated by Django 4.0.6 on 2022-11-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customer_britday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='types',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
