# Generated by Django 4.0.6 on 2022-07-31 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['email'], 'verbose_name': 'account', 'verbose_name_plural': 'account'},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'address', 'verbose_name_plural': 'Adresses'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'customer', 'verbose_name_plural': 'customers'},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'producer', 'verbose_name_plural': 'producers'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'request', 'verbose_name_plural': 'requests'},
        ),
        migrations.AlterModelOptions(
            name='telephone',
            options={'verbose_name': 'telephone', 'verbose_name_plural': 'phones'},
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='core/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='address',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
