# Generated by Django 4.0.6 on 2022-08-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_request_alter_ticket_request'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
