# Generated by Django 4.0.6 on 2022-07-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_category_event_category_and_more'),
        ('customer', '0008_rename_type_address_types'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='request',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='telephone',
            name='account_id',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Producer',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Telephone',
        ),
    ]
