# Generated by Django 4.0.6 on 2022-07-31 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_rename_status_request_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telephone',
            name='account_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
