# Generated by Django 4.0.6 on 2022-08-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_account_date_joined_alter_address_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(default='', max_length=150),
        ),
    ]
