# Generated by Django 4.0.6 on 2022-08-09 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_alter_address_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='account_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
