# Generated by Django 4.0.6 on 2022-08-13 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_account_groups_account_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account_id',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='producer',
            old_name='account_id',
            new_name='account',
        ),
    ]
