# Generated by Django 4.0.6 on 2022-07-31 01:22

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_account_options_alter_address_options_and_more'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('batck_start_date', models.DateTimeField(verbose_name='batck start date')),
                ('batck_stop_date', models.DateTimeField(verbose_name='batck start date')),
                ('description', models.CharField(default='', max_length=150)),
                ('is_active', models.BooleanField(verbose_name=True)),
            ],
            options={
                'verbose_name': 'batch',
                'verbose_name_plural': 'batches',
                'ordering': ['event_id'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('in_room', models.BooleanField(default=True, verbose_name='in room')),
                ('date_end', models.DateTimeField(verbose_name='date end')),
                ('date_start', models.DateTimeField(verbose_name='date start')),
                ('description', models.CharField(default='', max_length=250)),
                ('is_virtual', models.BooleanField(default=False)),
                ('video_url', models.CharField(max_length=200, verbose_name='video url')),
                ('address_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customer.address')),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.producer')),
                ('telephone_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='customer.telephone')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['ticket_leasing_id'], 'verbose_name': 'stock', 'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_checked',
            field=models.DateTimeField(auto_now=True, verbose_name='last checked'),
        ),
        migrations.CreateModel(
            name='TicketLeasing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('descroption', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('store_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='store price')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='sale price')),
                ('student_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='student price')),
                ('batck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.batck')),
            ],
            options={
                'ordering': ['batck_id'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('is_student', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.request')),
                ('ticket_leasing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.ticketleasing')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'ordering': ['request_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, default='', max_length=200, upload_to='core/covers/%Y/%m/%d/')),
                ('alt_text', models.CharField(max_length=150)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('event_category', models.ManyToManyField(to='event.event')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='event.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='batck',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='stock',
            name='ticket_leasing_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.ticketleasing'),
        ),
    ]
