# Generated by Django 4.0.6 on 2022-07-31 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_batck_event_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='event_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='address_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='producer_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='telephone_id',
        ),
        migrations.RemoveField(
            model_name='image',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='ticket_leasing_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_leasing_id',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='batck_id',
        ),
        migrations.DeleteModel(
            name='Batck',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
        migrations.DeleteModel(
            name='TicketLeasing',
        ),
    ]
