# Generated by Django 4.0.6 on 2022-07-31 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='level',
        ),
        migrations.RemoveField(
            model_name='category',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='category',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='category',
            name='tree_id',
        ),
    ]
