# Generated by Django 4.0.6 on 2022-10-16 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('src', models.ImageField(max_length=200, upload_to='covers/%Y/%m/%d/banner')),
                ('alt', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footerHtml', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LogoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=250)),
                ('srcImg', models.ImageField(blank=True, max_length=200, upload_to='covers/%Y/%m/%d/logoLink')),
            ],
        ),
        migrations.CreateModel(
            name='MenuLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=250)),
                ('newTab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('banner', models.ManyToManyField(blank=True, to='page.banner')),
                ('footer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.footer')),
                ('logoLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.logolink')),
                ('menuLink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.menulink')),
            ],
        ),
    ]
