# Generated by Django 4.0.6 on 2022-10-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ManyToManyField(to='page.banner'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='logoLink',
        ),
        migrations.AddField(
            model_name='page',
            name='logoLink',
            field=models.ManyToManyField(to='page.logolink'),
        ),
        migrations.RemoveField(
            model_name='page',
            name='menuLink',
        ),
        migrations.AddField(
            model_name='page',
            name='menuLink',
            field=models.ManyToManyField(to='page.menulink'),
        ),
    ]
