# Generated by Django 4.0.6 on 2022-10-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_banner_remove_page_logolink_page_logolink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='logoLink',
        ),
        migrations.AddField(
            model_name='page',
            name='logoLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.logolink'),
        ),
    ]
