# Generated by Django 4.0.6 on 2022-10-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_page_logolink_page_logolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
