# Generated by Django 4.0.6 on 2022-11-05 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_page_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='banner',
            new_name='banners',
        ),
    ]
