# Generated by Django 4.0.6 on 2022-11-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_rename_banner_page_banners'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='alt_text',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='src_img',
            field=models.ImageField(max_length=200, null=True, upload_to='footer/%Y/%m/%d/banner'),
        ),
    ]
