# Generated by Django 4.0.6 on 2022-11-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_footer_alt_text_footer_src_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='src_img',
            field=models.ImageField(max_length=200, null=True, upload_to='covers/footer/%Y/%m/%d/banner'),
        ),
    ]
