# Generated by Django 4.0.6 on 2022-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_alter_footer_src_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='src_img',
            field=models.ImageField(max_length=200, null=True, upload_to='covers/%Y/%m/%d/footer'),
        ),
    ]
