# Generated by Django 4.0.6 on 2022-08-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, verbose_name='sale price'),
        ),
        migrations.AlterField(
            model_name='leasing',
            name='student_price',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=8, verbose_name='student price'),
        ),
    ]
