# Generated by Django 4.0.6 on 2022-08-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Batck',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='batck_stop_date',
            new_name='batch_stop_date',
        ),
    ]
