# Generated by Django 4.0.6 on 2022-08-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rename_batck_batch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_leasing_id',
            new_name='leasing',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='request_id',
            new_name='request',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_stop_date',
            field=models.DateTimeField(verbose_name='batch stop date'),
        ),
    ]
