# Generated by Django 4.0.6 on 2022-08-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_batch_percentage_alter_leasing_sale_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
