# Generated by Django 4.0.6 on 2022-08-24 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_ticket_request_delete_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'ticket', 'verbose_name_plural': 'tickets'},
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='request',
            new_name='requisition',
        ),
    ]
