# Generated by Django 4.0.6 on 2022-09-04 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.address'),
        ),
    ]
