# Generated by Django 4.0.6 on 2022-07-31 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='units_sold',
            field=models.IntegerField(default=0),
        ),
    ]
