# Generated by Django 4.0.6 on 2022-09-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_leasing_units_solid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasing',
            name='units_solid',
            field=models.IntegerField(default=0),
        ),
    ]
