# Generated by Django 4.0.6 on 2022-07-31 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_stock_units_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='status',
            new_name='is_active',
        ),
    ]
