# Generated by Django 4.0.6 on 2022-07-31 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_rename_status_ticket_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='event_category',
            new_name='events',
        ),
    ]
