# Generated by Django 4.0.6 on 2022-09-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_categories_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, to='event.category'),
        ),
    ]
