# Generated by Django 4.0.6 on 2022-09-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='event.category'),
        ),
    ]
