# Generated by Django 4.0.6 on 2022-09-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
    ]
