# Generated by Django 4.0.6 on 2022-08-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_remove_category_level_remove_category_lft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('complement', models.CharField(default='', max_length=150)),
                ('city', models.CharField(default='', max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('municipality_IBGE', models.IntegerField()),
                ('number', models.IntegerField()),
                ('roud', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('uf_ibge', models.IntegerField()),
                ('types', models.IntegerField()),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'adresses',
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='telephone_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='address_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='event.address'),
        ),
    ]
