# Generated by Django 4.0.6 on 2022-08-09 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_address_remove_event_telephone_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='producer_id',
            new_name='producer',
        ),
    ]
