# Generated by Django 4.0.6 on 2022-09-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='categories',
            field=models.ManyToManyField(null=True, to='event.category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
    ]
