# Generated by Django 4.0.6 on 2022-08-09 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_alter_event_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='event_id',
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
    ]
