# Generated by Django 4.0.6 on 2022-08-09 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_alter_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
