# Generated by Django 4.0.6 on 2022-08-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_remove_event_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
