# Generated by Django 4.0.6 on 2022-08-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(blank=True, default='', max_length=200, upload_to='core/covers/%Y/%m/%d/')),
                ('alt_text', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'image',
                'verbose_name_plural': 'images',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
    ]
