# Generated by Django 4.0.6 on 2022-08-09 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_image_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
    ]
