# Generated by Django 4.0.6 on 2022-08-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_alter_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='event.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
