# Generated by Django 4.0.6 on 2022-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_alter_event_image_alter_image_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='alt_text',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.ImageField(blank=True, default='', max_length=200, upload_to='covers/%Y/%m/%d/'),
        ),
    ]
