# Generated by Django 4.0.6 on 2022-08-13 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0022_remove_category_events_event_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batck',
            old_name='event_id',
            new_name='event',
        ),
    ]
