# Generated by Django 4.0.6 on 2022-08-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0023_rename_event_id_batck_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='batck',
            name='sales_qtd',
            field=models.IntegerField(default=99999),
        ),
    ]
