# Generated by Django 4.0.6 on 2022-08-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0024_batck_sales_qtd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketleasing',
            options={},
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='batck_id',
        ),
        migrations.AddField(
            model_name='batck',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=999, max_digits=3),
        ),
        migrations.AddField(
            model_name='ticketleasing',
            name='event',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.event'),
        ),
        migrations.AddField(
            model_name='ticketleasing',
            name='units',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='ticketleasing',
            name='units_solid',
            field=models.IntegerField(default=''),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
