# Generated by Django 4.0.6 on 2022-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0026_alter_batck_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batck',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default='999.00', max_digits=5),
        ),
    ]
