# Generated by Django 4.0.6 on 2022-08-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0030_alter_batck_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batck',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price'),
        ),
    ]
