# Generated by Django 4.0.6 on 2022-08-18 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0031_alter_batck_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batck',
            name='percentage',
        ),
    ]
