# Generated by Django 4.0.6 on 2022-08-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0032_remove_batck_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='batck',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default='', max_digits=6),
        ),
    ]
