# Generated by Django 4.0.6 on 2022-08-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0033_batck_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batck',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='sale_price',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='store_price',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='student_price',
        ),
    ]
