# Generated by Django 4.0.6 on 2022-08-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0034_remove_batck_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batck',
            name='batck_start_date',
        ),
        migrations.RemoveField(
            model_name='batck',
            name='batck_stop_date',
        ),
        migrations.RemoveField(
            model_name='batck',
            name='description',
        ),
        migrations.RemoveField(
            model_name='batck',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='batck',
            name='sales_qtd',
        ),
    ]
