# Generated by Django 4.0.6 on 2022-08-18 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0035_remove_batck_batck_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketleasing',
            name='descroption',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='units',
        ),
        migrations.RemoveField(
            model_name='ticketleasing',
            name='units_solid',
        ),
    ]
