# Generated by Django 4.0.6 on 2022-08-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0036_remove_ticketleasing_descroption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
