# Generated by Django 4.0.6 on 2022-08-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0039_alter_batck_options_remove_batck_sequence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='in_room',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_virtual',
        ),
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video_url',
        ),
    ]
