# Generated by Django 4.0.6 on 2022-08-18 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0040_alter_event_options_remove_event_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
