# Generated by Django 4.0.6 on 2022-08-31 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_paid', models.BooleanField(default=False)),
                ('type_of_payment', models.DecimalField(decimal_places=0, max_digits=2, verbose_name='type of payment')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'requisition',
                'verbose_name_plural': 'requisitions',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='sale price')),
                ('code', models.CharField(max_length=255)),
                ('is_student', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('leasing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.leasing')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
            },
        ),
    ]
